# Generated by Django 3.2 on 2021-12-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysalary',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='modified time'),
        ),
        migrations.AlterField(
            model_name='rewarddeduction',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='modified time'),
        ),
        migrations.AlterField(
            model_name='weeklysalary',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='modified time'),
        ),
    ]
