# Generated by Django 3.2 on 2021-12-17 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0001_initial'),
        ('salary', '0002_auto_20211216_2336'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weeklysalary',
            unique_together={('courier', 'from_date', 'to_date')},
        ),
    ]
