# Generated by Django 3.2 on 2021-12-17 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0001_initial'),
        ('salary', '0003_alter_weeklysalary_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysalary',
            name='courier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_salaries', to='courier.courier', verbose_name='courier'),
        ),
        migrations.AlterField(
            model_name='weeklysalary',
            name='courier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekly_salaries', to='courier.courier', verbose_name='courier'),
        ),
    ]
