# Generated by Django 3.2 on 2021-12-16 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateField(auto_now_add=True, verbose_name='created time')),
                ('modified_time', models.DateField(auto_now=True, verbose_name='created time')),
                ('start_time', models.TimeField(auto_now_add=True, verbose_name='start time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='end time')),
                ('price', models.IntegerField(verbose_name='price')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='courier.courier', verbose_name='courier')),
            ],
            options={
                'verbose_name': 'trip',
                'verbose_name_plural': 'trips',
                'db_table': 'trip',
            },
        ),
    ]
