# Generated by Django 3.2 on 2021-12-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created time'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='modified_time',
            field=models.DateField(auto_now=True, verbose_name='modified time'),
        ),
    ]
