# Generated by Django 3.2 on 2021-12-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_auto_20211216_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='modified time'),
        ),
    ]
