# Generated by Django 3.2 on 2021-12-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=40, verbose_name='last name')),
            ],
            options={
                'verbose_name': 'courier',
                'verbose_name_plural': 'couriers',
                'db_table': 'courier',
            },
        ),
    ]
